### ISSUE TITLE
[Move] Antalpha Hacker House in Shanghai

### ISSUE THREAD

**Issue by wrx1234** [Antalpha-Labs/HackerHouse#14]
# 上海 Antalpha Hacker House

**Antalpha 支持，Move 开发者大会周边 Hacker House**

在 2024 年 Move 开发者大会即将举行之际，我们诚挚邀请所有的 Move 开发者聚集上海，参与 Hacker House 活动，共同碰撞创意和思路。

**地点：** Move 开发者大会周边（上海市徐汇区）

**时间：** 2024 年 1 月 12 日至 15 日（4 天3晚）

### **项目目标：**

- 吸引更多开发者了解和入门 Move 生态
- 介绍 Antalpha Hacker House 的理念和过往项目
- 基于 Move 生态，从技术、产品、运营等多角度探索新机会，设计出创新的应用和产品

### **项目计划：**

- 第一天：破冰与分享
    1. 欢迎和介绍
        - 主持人致辞，介绍活动的目的和日程安排。
    2. 自我介绍和主题分享
        - 每位参与者进行自我介绍，并分享他们感兴趣的主题或想要探索的问题。
    3. 团队组建
        - 参与者根据兴趣和主题选择合适的讨论方向，组成讨论小组。

- 第二、三天：学习、分享与交流
    1. 参与 Move 大会会场的学习活动
    2. 晚间分享会
        - 每晚 9 点，在 Hacker House 场地进行今日所学的简短分享（每人 2-3 分钟）
    3. 专业 Move 开发者问答环节

- 第四天：团队活动与演示
    1. 进行团队建设活动
    2. 团队成员分享收获和感受

### **运营组成员：**

- Vanessa：制定 Hacker House 规划，协调相关资源
- UVD：项目分享和嘉宾
- Xuan：协调现场工作

### **联系方式：**

Antalpha：[qijin@antalpha.com](mailto:qijin@antalpha.com)

上海 Hacker House：[vanessaaalian@gmail.com](mailto:vanessaaalian@gmail.com)

**Comment by qijinzing** [comment]
已通过
活动时间：2024年1月13-14
请把erc地址发到这里

**Comment by wrx1234** [comment]
上海House收款地址： 0x05b048a8689d0b4f28f32fb620c2a4d6ab35b159（erc20）

**Comment by qijinzing** [comment]
圆满落幕，转账hash：https://etherscan.io/tx/0xe963eafcd08affd3b448c7f392146f441565d8eff65f6a62238c035cb1dd6939
