### ISSUE TITLE
Antalpha Hacker House in Nanning

### ISSUE THREAD

**Issue by lazy1523** [Antalpha-Labs/HackerHouse#2]
目标：集结一群对EVM和区块链技术有兴趣的开发者，共同为EVM带来的新机会开发出创新的应用和产品。
时间：11月20-11月27号，Demoday时间为11月26号，共计8天
人数：10人
地点：南宁市（具体地点另行通知）
活动原则：安全第一,提供单人的住宿环境，需集体行动，原则上不允许单独外出。
主办方会策划以下集体活动：
1、讲师授课分享（邀请来自黑客松冠军、Linux红帽工程师等讲师分享）
2、临江小酌 & 脑暴
3、青山秋游
4、CodingDay &导师现场指导
5、每日8.30 - 9点早餐时间，边吃边同步项目进度与难点

具体活动时间表
Day 1 -
·9:00 AM - 12:00 AM 注册
·14:00 AM - 15:30 AM 活动介绍和参与者互相认识并组队
·16:00 PM - 17:30 PM 团队idea展示
·20:00 PM  临江3小时露营&烧烤晚宴（来自南宁的欢迎仪式）

Day 2 -
·9:00 AM - 10:00 AM 大咖分享
·集体Coding
·5:00 PM - 6:00 PM 头脑风暴会议（idea优化）
·20:00PM 临江小酌

Day 3 -
·9:00 AM - 11:00 AM: 项目进展展示
·10:30 AM - 12:30 PM: 头脑风暴会议（项目优化）
·集体coding

Day 4 -
·9:00 AM - 14:00 PM: 青秀山秋游
·集体Coding

Day 5 -
·9:00 AM - 11:00 AM: 大咖分享
·集体Coding
·20:00PM 临江小酌 
 
Day 6 - 
·9:00 AM - 11:00 AM 项目进展展示
·2:00 PM - 4:00 PM 大咖分享
·集体Coding

Day 7 - 项目演示和闭幕
9:00 AM - 11:00 AM 项目展示及评选
2:00 PM - 4:00 PM 聚餐

Day 8 - Hacker休息时间
	     自由行动与休息

**Comment by qijinzing** [comment]
已通过
活动时间：11月20号 - 11月26号
也请把erc地址发这里，后续会把支持资金转给nanning hackerhouse组织者

**Comment by lazy1523** [comment]
0x46b6F87DeBD8f7607d00Df47C31D2dC6D9999999


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: qijin ***@***.***>
发送时间: 2023年11月7日 16:09
收件人: Antalpha-Labs/HackerHouse ***@***.***>
抄送: zisu ***@***.***>; Author ***@***.***>
主题: Re: [Antalpha-Labs/HackerHouse] Antalpha Hacker House in Nanning (Issue #2)


已通过
活动时间：11月20号 - 11月26号
也请把erc地址发这里，后续会把支持资金转给nanning hackerhouse组织者

―

**Comment by qijinzing** [comment]
报名不理想，暂缓组织，等准备充分后再开展。

**Comment by qijinzing** [comment]
报名不理想，暂缓组织，等准备充分后再开展。
