### ISSUE TITLE
Antalpha Hacker House in Chiangmai

### ISSUE THREAD

**Issue by metanomad21** [Antalpha-Labs/HackerHouse#3]
# Antalpha Hacker House in Chiangmai
## TON/TG mini app/TG Bot IdeaHouse

**目标**：基于TON/TG生态，从技术/产品/运营等多角度探索TON/TG生态的新机会，设计出创新的应用和产品

**日期**：2023年12月21日-12月26日  
**人数**：每天10-16 
**时长**：6天  
**形式**：分享 & 脑爆  
**地点**：NP Chiangmai 数字游民空间（36/5 Nimmanhaemin Soi 11 Chiangmai）

### 集体活动：
1. 嘉宾分享
   - TON/TG生态的项目方或者专家进行产品/市场趋势的介绍和分享
2. 每天基于TON/TG生态的不同子主题的产品脑暴
   - **2.1 流程**
     - 进行自我介绍和想做的主题分享
     - 现场交流组队和脑爆
     - 产品的BRD文档撰写
   - **2.2 产出**
     - 相对比较完整的 BRD or PRD，原型图（草稿）
3. 古城city walk
4. 待定

**报名**：Ticket 形式  
**分享嘉宾**：提供餐补  
**每天子主题不同单独报名**  
**提前报名 价格**：免费  
**现场报名 价格**：现场购买咖啡一杯~
**报名链接**：lu.ma/待定

### 每日子主题：
- 待定
``

**Comment by qijinzing** [comment]
已通过
活动时间：2023年12月21日-12月26日
请把erc地址发到这里

**Comment by metanomad21** [comment]
0x6f2a0bff2ed49911436d13bf5dd909f10599e913

**Comment by qijinzing** [comment]
已转 https://etherscan.io/tx/0x29fcd9ea2a3c7a29f8342c52939b9cee638cb12f96697a4c238d8630a6a40a67

**Comment by qijinzing** [comment]
视频 https://www.youtube.com/playlist?list=PLbQFt1T_44DyCi0u5YRUQfy6-82ekMiMf
活动link：https://lu.ma/dvubhm9c
